// <auto-generated />
namespace webtruyen.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addlaai : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlaai));
        
        string IMigrationMetadata.Id
        {
            get { return "202203031638579_addlaai"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
