// <auto-generated />
namespace webtruyen.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class asddas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asddas));
        
        string IMigrationMetadata.Id
        {
            get { return "202203220844563_asddas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
